# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{failurous-ruby}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mikko Nyl\303\251n", "Tero Parviainen", "Antti Forsell"]
  s.date = %q{2010-11-02}
  s.description = %q{failurous-ruby is a Ruby notifier for sending notifications to Failurous}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "doc/Failurous.html",
     "doc/Failurous/Config.html",
     "doc/Failurous/FailNotification.html",
     "doc/Failurous/FailNotifier.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "failurous-ruby.gemspec",
     "lib/failurous.rb",
     "lib/failurous/config.rb",
     "lib/failurous/fail_notification.rb",
     "lib/failurous/fail_notifier.rb",
     "spec/fail_notification_spec.rb",
     "spec/fail_notifier_spec.rb",
     "spec/failurous_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/matchers/have_field.rb",
     "spec/support/matchers/have_section.rb"
  ]
  s.homepage = %q{http://github.com/mnylen/failurous-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby notifier for Failurous}
  s.test_files = [
    "spec/fail_notification_spec.rb",
     "spec/fail_notifier_spec.rb",
     "spec/failurous_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/matchers/have_field.rb",
     "spec/support/matchers/have_section.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

